name: infinity_link
description: "Infinity Link - Firebase Authentication & Mock API Integration (Web App)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP client for Firebase REST API and mock API calls
  http: ^1.1.0
  
  # State management for authentication and UI state
  provider: ^6.1.1
  
  # Environment variables support
  flutter_dotenv: ^5.1.0
  
  # Material Design icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets for environment variables
  assets:
    - .env
