services:
  - type: web
    name: infinity-link
    env: dart
    buildCommand: flutter build web --release
    staticPublishPath: build/web
    envVars:
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: FIREBASE_APP_ID
        sync: false
      - key: FIREBASE_MEASUREMENT_ID
        sync: false
      - key: MOCK_API_BASE_URL
        value: https://mock-server-6yyu.onrender.com
      - key: DEBUG_MODE
        value: false
      - key: ENABLE_LOGGING
        value: true
